audite:
  restart: always
  build: ./audite
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - /usr/src/app
    - /usr/src/app/static
    - /var/www/audite/media:/usr/src/app/media
    - /var/www/audite.tk/static:/var/www/audite.tk/static
  env_file: .env
  environment:
    DEBUG: 'True'
  command: /usr/local/bin/gunicorn audite.wsgi:application -w 2 -b :8000

celery:
  restart: always
  build: ./audite
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - /usr/src/app
    - /usr/src/app/static
    - /var/www/audite/media:/usr/src/app/media
    - /var/www/audite.tk/static:/var/www/audite.tk/static
  env_file: .env
  environment:
    DEBUG: 'True'
  command: ./run_celery.sh

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/www/audite.tk/static/
    - /www/media
    - /etc/letsencrypt:/etc/letsencrypt
  volumes_from:
    - audite
  links:
    - audite:audite

postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"
  volumes:
    - redisdata:/data
