# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 20:37
from __future__ import unicode_literals

import audite.apps.songs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('name_slug', models.SlugField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('name_slug', models.SlugField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, height_field=400, null=True, upload_to=audite.apps.songs.models.upload_image, width_field=400)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('name_slug', models.SlugField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('calification', models.IntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Album')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Artist'),
        ),
    ]
