# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 22:47
from __future__ import unicode_literals

import audite.apps.songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20161109_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='img_height',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='img_width',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, height_field='img_height', null=True, upload_to=audite.apps.songs.models.upload_image, width_field='img_width'),
        ),
    ]
