# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:02
from __future__ import unicode_literals

import audite.apps.songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20161112_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='img_width',
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=audite.apps.songs.models.upload_image),
        ),
    ]
